version: "3.8"
services:
  movie-app:
    image: "movie-app"
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"


